const reasons = [
 "Por tu sonrisa que ilumina mi día.",
  "Por tu forma de ver la vida con optimismo.",
  "Por cómo me haces sentir amado.",
  "Por tu paciencia cuando no entiendo.",
  "Por tus abrazos que me reconfortan.",
  "Por tu voz al despertar.",
  "Por tu olor al dormir.",
  "Por cómo me miras cuando hablo.",
  "Por tu risa que contagia felicidad.",
  "Por tu forma de amar sin condiciones.",
  "Por tu forma de dormir tan tranquila.",
  "Por tus besos de buenas noches.",
  "Por cómo me defiendes sin decir nada.",
  "Por tu olor que no quiero olvidar.",
  "Por tu forma de abrazarme fuerte.",
  "Por tu voz al teléfono por la noche.",
  "Por tu mirada cómplice en silencio.",
  "Por tu forma de amarme sin pedir nada a cambio.",
  "Por tu forma de escuchar sin juzgar.",
  "Por tu forma de soñar conmigo.",
  "Por tu forma de reírte de mis tonterías.",
  "Por cómo me haces sentir en casa.",
  "Por tu forma de abrazar mis defectos.",
  "Por tu forma de creer en mí.",
  "Por tu forma de alegrarte mis días.",
  "Por tu forma de llamar mi atención.",
  "Por tu forma de sonreírme al verme.",
  "Por tu forma de sorprenderme con detalles.",
  "Por tu forma de dormir abrazada a mí.",
  "Por tu forma de entender mis silencios.",
  "Por tu forma de amarme sin medida.",
  "Por tu forma de quererme tal como soy.",
  "Por tu forma de ver el mundo con amor.",
  "Por tu forma de querer construir algo bonito.",
  "Por tu forma de hacerme sentir único.",
  "Por tu forma de mirarme como si no hubiera nadie más.",
  "Por tu forma de alegrarte con mis logros.",
  "Por tu forma de apoyarme sin dudar.",
  "Por tu forma de reírte de ti misma.",
  "Por tu forma de perdonarme sin reproches.",
  "Por tu forma de abrazar mis miedos.",
  "Por tu forma de quererme incluso cuando no soy perfecto.",
  "Por tu forma de ser luz en mi vida.",
  "Por tu forma de alegrarte cuando te veo feliz.",
  "Por tu forma de cuidarme con cariño.",
  "Por tu forma de amarme con ternura.",
  "Por tu forma de soñar en grande conmigo.",
  "Por tu forma de reírme sin parar contigo.",
  "Por tu forma de abrazar mis locuras.",
  "Por tu forma de hacerme sentir que puedo con todo.",
  "Por tu forma de sonreírme sin razón.",
  "Por tu forma de amarme con pasión.",
  "Por tu forma de recordarme que soy importante.",
  "Por tu forma de ver el amor como algo puro.",
  "Por tu forma de emocionarte con pequeñas cosas.",
  "Por tu forma de alegrarte cuando me ves feliz.",
  "Por tu forma de reírme con tus ocurrencias.",
  "Por tu forma de abrazar mis días tristes.",
  "Por tu forma de amarme con respeto.",
  "Por tu forma de hacerme reír cuando no quiero.",
  "Por tu forma de quererme incluso en mis días oscuros.",
  "Por tu forma de verme como el mejor.",
  "Por tu forma de emocionarte conmigo.",
  "Por tu forma de alegrarte con mis locuras.",
  "Por tu forma de soñar conmigo en silencio.",
  "Por tu forma de alegrarme la vida.",
  "Por tu forma de cuidarme sin que me dé cuenta.",
  "Por tu forma de reírme con tu voz.",
  "Por tu forma de amarme sin pedir explicaciones.",
  "Por tu forma de abrazarme fuerte cuando lloro.",
  "Por tu forma de alegrarte cuando llego.",
  "Por tu forma de emocionarte con una mirada.",
  "Por tu forma de amarme con la mirada.",
  "Por tu forma de alegrarte con mis tonterías.",
  "Por tu forma de verme como tu refugio.",
  "Por tu forma de abrazarme en silencio.",
  "Por tu forma de reírme con tu cara.",
  "Por tu forma de alegrarte con mis ocurrencias.",
  "Por tu forma de abrazar mis silencios.",
  "Por tu forma de alegrarme con una canción.",
  "Por tu forma de amarme con dulzura.",
  "Por tu forma de reírme con tus abrazos.",
  "Por tu forma de alegrarte con mis abrazos.",
  "Por tu forma de alegrarte con mi voz.",
  "Por tu forma de emocionarme con tu mirada.",
  "Por tu forma de abrazarme cuando no quiero.",
  "Por tu forma de alegrarte con mis tonterías.",
  "Por tu forma de alegrarme con tu risa.",
  "Por tu forma de alegrarte con mi presencia.",
  "Por tu forma de abrazarme con cariño.",
  "Por tu forma de alegrarte con mi sonrisa.",
  "Por tu forma de alegrarte con mis abrazos.",
  "Por tu forma de alegrarte con mi voz.",
  "Por tu forma de alegrarte con mi presencia.",
  "Por tu forma de alegrarte con mis locuras.",
  "Por tu forma de alegrarte con mi cariño.",
  "Por tu forma de alegrarte con mi risa.",
  "Por tu forma de alegrarte con mi amor.",
  "Por tu forma de alegrarte con mi presencia.",
  "Por tu forma de alegrarte con mi sonrisa.",
  "Por tu forma de alegrarte con mi voz.",
  "Por tu forma de alegrarte con mi mirada.",
  "Por tu forma de alegrarte con mi abrazo.",
  "Por tu forma de alegrarte con mi amor.",
  "Por tu forma de alegrarte con mi presencia.",
  "Por tu forma de alegrarte con mi sonrisa.",
  "Por tu forma de alegrarte con mi voz.",
  "Por tu forma de alegrarte con mi mirada.",
  "Por tu forma de alegrarte con mi abrazo.",
  "Por tu forma de alegrarte con mi amor."
];

const container = document.getElementById('reasons-container');

reasons.forEach((reason, index) => {
  const card = document.createElement('div');
  card.className = 'card';
  card.innerHTML = `
    <div class="card-number">${index + 1}</div>
    <div class="card-text">${reason}</div>
  `;
  container.appendChild(card);
});

// Reproducir música al hacer clic en la página
document.addEventListener('click', () => {
  const audio = document.getElementById('bg-music');
  audio.play().catch(e => console.log("Reproducción automática bloqueada."));
});